import {
  pgTable,
  serial,
  bigserial,
  integer,
  varchar,
  text,
  timestamp,
  pgEnum,
  jsonb,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { organizationsTable } from "./organizations";
import { usersTable } from "./users";

/**
 * Mac Mini Helper foundation — see
 * `artifacts/offloadr-api/docs/mac-mini-helper-architecture.md`.
 *
 * V1 ships three tables:
 *   - helper_devices         : a paired Mac Mini / Helper instance
 *   - helper_pairing_codes   : one-time codes generated by admins
 *   - helper_events          : append-only telemetry stream
 *
 * The actual bearer token is never stored — only its sha256 hash.
 * The plaintext token is shown to the operator exactly once at
 * pair time and then lives only in the Mac's Keychain.
 */

export const helperDeviceStatusEnum = pgEnum("helper_device_status", [
  "active",
  "revoked",
]);

export const helperDevicesTable = pgTable(
  "helper_devices",
  {
    id: serial("id").primaryKey(),
    organizationId: integer("organization_id")
      .notNull()
      .references(() => organizationsTable.id, { onDelete: "cascade" }),
    deviceLabel: varchar("device_label", { length: 120 }).notNull(),
    status: helperDeviceStatusEnum("status").notNull().default("active"),
    apiKeyHash: varchar("api_key_hash", { length: 64 }).notNull(),
    hostname: varchar("hostname", { length: 255 }),
    osVersion: varchar("os_version", { length: 64 }),
    helperVersion: varchar("helper_version", { length: 32 }),
    pairedAt: timestamp("paired_at", { withTimezone: true }).defaultNow().notNull(),
    pairedByUserId: integer("paired_by_user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "restrict" }),
    lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true }),
    lastUptimeSec: integer("last_uptime_sec"),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedByUserId: integer("revoked_by_user_id").references(() => usersTable.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    apiKeyHashUnique: uniqueIndex("helper_devices_api_key_hash_unique").on(t.apiKeyHash),
    orgIdx: index("helper_devices_org_idx").on(t.organizationId),
  }),
);

export const helperPairingCodesTable = pgTable(
  "helper_pairing_codes",
  {
    id: serial("id").primaryKey(),
    organizationId: integer("organization_id")
      .notNull()
      .references(() => organizationsTable.id, { onDelete: "cascade" }),
    code: varchar("code", { length: 16 }).notNull(),
    deviceLabel: varchar("device_label", { length: 120 }).notNull(),
    createdByUserId: integer("created_by_user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "restrict" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    consumedDeviceId: integer("consumed_device_id").references(
      () => helperDevicesTable.id,
      { onDelete: "set null" },
    ),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    codeUnique: uniqueIndex("helper_pairing_codes_code_unique").on(t.code),
    orgIdx: index("helper_pairing_codes_org_idx").on(t.organizationId),
  }),
);

export const helperEventsTable = pgTable(
  "helper_events",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    deviceId: integer("device_id")
      .notNull()
      .references(() => helperDevicesTable.id, { onDelete: "cascade" }),
    organizationId: integer("organization_id")
      .notNull()
      .references(() => organizationsTable.id, { onDelete: "cascade" }),
    // Client-generated ULID/UUID. Used as the idempotency key so
    // network retries don't double-write the same event.
    eventId: varchar("event_id", { length: 64 }).notNull(),
    kind: varchar("kind", { length: 64 }).notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}),
    sourceLabel: varchar("source_label", { length: 120 }),
    // ts is what the helper reports; receivedAt is the server clock.
    // Disagreement between the two is itself useful telemetry.
    ts: timestamp("ts", { withTimezone: true }).notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    // Idempotency scoped per-device. A regression in client event-id
    // generation can never cause cross-device drops.
    deviceEventIdUnique: uniqueIndex("helper_events_device_event_id_unique").on(
      t.deviceId,
      t.eventId,
    ),
    deviceTsIdx: index("helper_events_device_ts_idx").on(t.deviceId, t.ts),
    orgTsIdx: index("helper_events_org_ts_idx").on(t.organizationId, t.ts),
  }),
);

export const insertHelperDeviceSchema = createInsertSchema(helperDevicesTable).omit({
  id: true,
  createdAt: true,
  pairedAt: true,
  lastHeartbeatAt: true,
  lastUptimeSec: true,
  revokedAt: true,
  revokedByUserId: true,
});

export type InsertHelperDevice = z.infer<typeof insertHelperDeviceSchema>;
export type HelperDevice = typeof helperDevicesTable.$inferSelect;
export type HelperDeviceStatus = "active" | "revoked";
export type HelperPairingCode = typeof helperPairingCodesTable.$inferSelect;
export type HelperEvent = typeof helperEventsTable.$inferSelect;
